apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../base/web/deployment.yaml
  - ../../base/web/service.yaml
  - ../../base/web/hpa.yaml
  - ../../base/api/deployment.yaml
  - ../../base/api/service.yaml
  - ../../base/api/hpa.yaml
  - ../../base/socket-server/deployment.yaml
  - ../../base/socket-server/service.yaml
  - ../../base/queue-worker/deployment.yaml
  - ../../base/redis/deployment.yaml
  - ../../base/postgres/deployment.yaml
  - ../../base/traefik/ingress.yaml
  - ../../base/keda/scaledobject-agent-worker.yaml
  - ../../base/monitoring/alert-rules.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: web
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: api
