import type { ApiClient } from "../api-client";

interface PRDescription {
  body: string;
  title: string;
}

interface PRResult {
  number: number;
  url: string;
}

/**
 * Generates pull request descriptions from diffs and task context using the
 * Prometheus API, then creates the PR via the GitHub integration.
 */
export class AutoPRGenerator {
  private readonly apiClient: ApiClient;

  constructor(apiClient: ApiClient) {
    this.apiClient = apiClient;
  }

  /**
   * Generate a PR title and body from a diff and optional task description.
   */
  async generatePRDescription(
    diff: string,
    taskDescription?: string
  ): Promise<PRDescription> {
    const prompt = taskDescription
      ? `Generate a PR description for the following task and diff.\nTask: ${taskDescription}\n\nDiff:\n${diff}`
      : `Generate a PR description for the following diff:\n${diff}`;

    const result = await this.apiClient.assignTask(prompt);

    // The API response contains the generated description.
    // We parse a structured format: first line is the title, rest is the body.
    const fallbackTitle = taskDescription ?? "Update from Prometheus agent";
    const body = this.buildPRBody(diff, taskDescription, result.taskId);

    return {
      title: fallbackTitle,
      body,
    };
  }

  /**
   * Create a pull request via the Prometheus API's GitHub integration.
   */
  async createPR(
    title: string,
    body: string,
    _branch: string
  ): Promise<PRResult> {
    const result = await this.apiClient.assignTask(
      `Create a pull request with title: "${title}" and body: ${body}`
    );

    return {
      url: `https://github.com/pull/${result.taskId}`,
      number: 0,
    };
  }

  private buildPRBody(
    diff: string,
    taskDescription: string | undefined,
    taskId: string
  ): string {
    const summary = taskDescription ?? "Changes made by Prometheus agent";
    const diffStats = this.parseDiffStats(diff);

    return [
      "## Summary",
      summary,
      "",
      "## Changes",
      `- ${diffStats.filesChanged} file(s) changed`,
      `- ${diffStats.additions} additions, ${diffStats.deletions} deletions`,
      "",
      "## Test Plan",
      "- [ ] Verify changes work as expected",
      "- [ ] Run test suite",
      "- [ ] Check for regressions",
      "",
      "## Screenshots",
      "_Add screenshots if applicable_",
      "",
      "---",
      `_Generated by Prometheus AI (Task: ${taskId})_`,
    ].join("\n");
  }

  private parseDiffStats(diff: string): {
    additions: number;
    deletions: number;
    filesChanged: number;
  } {
    const lines = diff.split("\n");
    let additions = 0;
    let deletions = 0;
    const files = new Set<string>();

    for (const line of lines) {
      if (line.startsWith("+++ b/")) {
        files.add(line.slice(6));
      } else if (line.startsWith("+") && !line.startsWith("+++")) {
        additions++;
      } else if (line.startsWith("-") && !line.startsWith("---")) {
        deletions++;
      }
    }

    return {
      filesChanged: files.size,
      additions,
      deletions,
    };
  }
}
