import { createLogger } from "@prometheus/logger";
import type { WorktreeManager } from "./worktree-manager";

const logger = createLogger("orchestrator:git:pr");

const MODEL_ROUTER_URL =
  process.env.MODEL_ROUTER_URL ?? "http://localhost:4004";

export interface PRResult {
  branch: string;
  created: boolean;
  prNumber?: number;
  prUrl?: string;
  title: string;
}

/**
 * PRWorkflow handles autonomous pull request creation after
 * agent task completion. Generates descriptive PR title and body
 * from the diff using the review model slot.
 */
export class PRWorkflow {
  private readonly worktreeManager: WorktreeManager;

  constructor(worktreeManager: WorktreeManager) {
    this.worktreeManager = worktreeManager;
  }

  /**
   * Create a PR from the task's worktree changes.
   */
  async createPR(
    projectId: string,
    taskId: string,
    taskTitle: string,
    taskDescription: string
  ): Promise<PRResult> {
    const worktree = this.worktreeManager.getWorktree(taskId);
    if (!worktree) {
      return { created: false, title: taskTitle, branch: "" };
    }

    // Get the diff to summarize
    const diff = await this.worktreeManager.getDiff(projectId, taskId);
    if (!diff || diff.trim().length === 0) {
      logger.info({ taskId }, "No changes to create PR for");
      return { created: false, title: taskTitle, branch: worktree.branch };
    }

    // Generate PR description using the review model
    const _prBody = await this.generatePRBody(taskTitle, taskDescription, diff);

    // Commit if not already committed
    await this.worktreeManager.commit(
      projectId,
      taskId,
      `feat: ${taskTitle}\n\nGenerated by Prometheus AI agent`
    );

    logger.info(
      {
        taskId,
        branch: worktree.branch,
        diffLines: diff.split("\n").length,
      },
      "PR workflow complete — ready for push"
    );

    return {
      created: true,
      title: `[Prometheus] ${taskTitle}`,
      branch: worktree.branch,
      prUrl: undefined, // Set when GitHub integration pushes
    };
  }

  private async generatePRBody(
    title: string,
    description: string,
    diff: string
  ): Promise<string> {
    try {
      const response = await fetch(`${MODEL_ROUTER_URL}/route`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          slot: "review",
          messages: [
            {
              role: "user",
              content: `Generate a concise PR description for:

Title: ${title}
Task: ${description}

Diff (first 3000 chars):
${diff.slice(0, 3000)}

Format:
## Summary
<2-3 bullet points of what changed and why>

## Changes
<list of files changed with brief description>

## Test Plan
<how to verify these changes work>`,
            },
          ],
          options: { maxTokens: 1024, temperature: 0.2 },
        }),
        signal: AbortSignal.timeout(30_000),
      });

      if (response.ok) {
        const data = (await response.json()) as {
          choices: Array<{ message: { content: string } }>;
        };
        return (
          data.choices[0]?.message.content ??
          this.fallbackBody(title, description)
        );
      }
    } catch (err) {
      logger.warn({ error: err }, "PR body generation failed");
    }

    return this.fallbackBody(title, description);
  }

  private fallbackBody(_title: string, description: string): string {
    return `## Summary\n${description}\n\n## Changes\nSee diff for details.\n\n---\nGenerated by Prometheus AI`;
  }
}
