import { createLogger } from "@prometheus/logger";
import { GitHubClient, modelRouterClient } from "@prometheus/utils";
import {
  type SemgrepResult,
  SemgrepScanner,
} from "../guardian/semgrep-scanner";
import type { WorktreeManager } from "./worktree-manager";

const logger = createLogger("orchestrator:git:pr");

export interface PRResult {
  branch: string;
  created: boolean;
  prNumber?: number;
  prUrl?: string;
  securityScan?: SemgrepResult;
  title: string;
}

/**
 * PRWorkflow handles autonomous pull request creation after
 * agent task completion. Generates descriptive PR title and body
 * from the diff using the review model slot, pushes the branch,
 * and creates a GitHub PR via the REST API.
 */
export class PRWorkflow {
  private readonly worktreeManager: WorktreeManager;
  private readonly github: GitHubClient;
  private readonly semgrepScanner: SemgrepScanner;

  constructor(worktreeManager: WorktreeManager) {
    this.worktreeManager = worktreeManager;
    this.github = new GitHubClient();
    this.semgrepScanner = new SemgrepScanner();
  }

  /**
   * Create a PR from the task's worktree changes.
   */
  async createPR(
    projectId: string,
    taskId: string,
    taskTitle: string,
    taskDescription: string,
    repoInfo?: { owner: string; repo: string; baseBranch?: string },
    sandboxId?: string
  ): Promise<PRResult> {
    const worktree = this.worktreeManager.getWorktree(taskId);
    if (!worktree) {
      return { created: false, title: taskTitle, branch: "" };
    }

    // Get the diff to summarize
    const diff = await this.worktreeManager.getDiff(projectId, taskId);
    if (!diff || diff.trim().length === 0) {
      logger.info({ taskId }, "No changes to create PR for");
      return { created: false, title: taskTitle, branch: worktree.branch };
    }

    // Run security scan before PR creation
    const scanResult = await this.runSecurityScan(sandboxId);

    // Generate PR description using the review model
    let prBody = await this.generatePRBody(taskTitle, taskDescription, diff);

    // Append security scan warnings to PR body if there are findings
    if (scanResult && scanResult.findings.length > 0) {
      const scanSummary = this.semgrepScanner.formatFindings(scanResult);
      prBody = `${prBody}\n\n---\n\n${scanSummary}`;

      if (this.semgrepScanner.shouldBlockPR(scanResult)) {
        logger.warn(
          {
            taskId,
            highFindings: scanResult.summary.high,
          },
          "Security scan found high-severity issues"
        );
      }
    }

    // Commit if not already committed
    await this.worktreeManager.commit(
      projectId,
      taskId,
      `feat: ${taskTitle}\n\nGenerated by Prometheus AI agent`
    );

    // Push branch to remote
    const pushResult = await this.worktreeManager.push(projectId, taskId);
    if (!pushResult.pushed) {
      logger.warn(
        { taskId, error: pushResult.error },
        "Push failed — PR created locally only"
      );
      return {
        created: true,
        title: `[Prometheus] ${taskTitle}`,
        branch: worktree.branch,
        securityScan: scanResult,
      };
    }

    // Create GitHub PR if repo info is available
    if (repoInfo?.owner && repoInfo?.repo) {
      try {
        const pr = await this.github.createPR({
          owner: repoInfo.owner,
          repo: repoInfo.repo,
          title: `[Prometheus] ${taskTitle}`,
          body: prBody,
          head: worktree.branch,
          base: repoInfo.baseBranch ?? "main",
        });

        logger.info(
          { taskId, prNumber: pr.prNumber, prUrl: pr.prUrl },
          "GitHub PR created"
        );

        return {
          created: true,
          title: `[Prometheus] ${taskTitle}`,
          branch: worktree.branch,
          prNumber: pr.prNumber,
          prUrl: pr.prUrl,
          securityScan: scanResult,
        };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        logger.warn({ taskId, error: msg }, "GitHub PR creation failed");
      }
    }

    logger.info(
      {
        taskId,
        branch: worktree.branch,
        diffLines: diff.split("\n").length,
      },
      "PR workflow complete — branch pushed"
    );

    return {
      created: true,
      title: `[Prometheus] ${taskTitle}`,
      branch: worktree.branch,
      securityScan: scanResult,
    };
  }

  /**
   * Run a semgrep security scan inside the sandbox. Returns the scan
   * result, or undefined if no sandbox is available.
   */
  async runSecurityScan(
    sandboxId?: string
  ): Promise<SemgrepResult | undefined> {
    if (!sandboxId) {
      logger.debug("No sandbox ID provided — skipping security scan");
      return undefined;
    }

    try {
      logger.info({ sandboxId }, "Running semgrep security scan");
      const result = await this.semgrepScanner.scan(sandboxId);

      logger.info(
        {
          sandboxId,
          high: result.summary.high,
          medium: result.summary.medium,
          low: result.summary.low,
          total: result.findings.length,
        },
        "Semgrep scan complete"
      );

      return result;
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      logger.warn({ sandboxId, error: msg }, "Security scan failed");
      return undefined;
    }
  }

  private async generatePRBody(
    title: string,
    description: string,
    diff: string
  ): Promise<string> {
    try {
      const response = await modelRouterClient.post<{
        choices: Array<{ message: { content: string } }>;
      }>("/route", {
        slot: "review",
        messages: [
          {
            role: "user",
            content: `Generate a concise PR description for:

Title: ${title}
Task: ${description}

Diff (first 3000 chars):
${diff.slice(0, 3000)}

Format:
## Summary
<2-3 bullet points of what changed and why>

## Changes
<list of files changed with brief description>

## Test Plan
<how to verify these changes work>`,
          },
        ],
        options: { maxTokens: 1024, temperature: 0.2 },
      });

      return (
        response.data.choices[0]?.message.content ??
        this.fallbackBody(title, description)
      );
    } catch (err) {
      logger.warn({ error: err }, "PR body generation failed");
    }

    return this.fallbackBody(title, description);
  }

  private fallbackBody(_title: string, description: string): string {
    return `## Summary\n${description}\n\n## Changes\nSee diff for details.\n\n---\nGenerated by Prometheus AI`;
  }
}
