import { createLogger } from "@prometheus/logger";
import type { SetupProjectEnvironmentData } from "@prometheus/queue";
import { EventPublisher } from "@prometheus/queue";

const logger = createLogger("queue-worker:setup-environment");
const publisher = new EventPublisher();

const SANDBOX_MANAGER_URL =
  process.env.SANDBOX_MANAGER_URL ?? "http://localhost:4006";

// ---------------------------------------------------------------------------
// Sandbox exec helper
// ---------------------------------------------------------------------------

interface ExecResult {
  exitCode: number;
  stderr: string;
  stdout: string;
}

async function execInSandbox(
  sandboxId: string,
  command: string,
  timeoutMs = 120_000
): Promise<ExecResult> {
  const response = await fetch(
    `${SANDBOX_MANAGER_URL}/sandbox/${sandboxId}/exec`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ command, timeout: timeoutMs }),
      signal: AbortSignal.timeout(timeoutMs + 5000),
    }
  );

  if (!response.ok) {
    const text = await response.text();
    return { exitCode: 1, stdout: "", stderr: text };
  }

  return (await response.json()) as ExecResult;
}

async function readSandboxFile(
  sandboxId: string,
  filePath: string
): Promise<string | null> {
  try {
    const result = await execInSandbox(
      sandboxId,
      `cat "${filePath}" 2>/dev/null`,
      10_000
    );
    return result.exitCode === 0 ? result.stdout : null;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Step results
// ---------------------------------------------------------------------------

export interface SetupResult {
  buildVerified: boolean;
  dependenciesInstalled: boolean;
  envFileCreated: boolean;
  stackDetected: boolean;
  techStack: {
    buildCommand: string;
    devCommand: string;
    frameworks: string[];
    isMonorepo: boolean;
    languages: string[];
    packageManager: string;
    suggestedPreset: string;
    testCommand: string;
  } | null;
}

// ---------------------------------------------------------------------------
// Step helpers (extracted to reduce cognitive complexity)
// ---------------------------------------------------------------------------

async function detectStack(
  sandboxId: string,
  projectId: string
): Promise<SetupResult["techStack"]> {
  const listResult = await execInSandbox(
    sandboxId,
    'find /workspace -maxdepth 3 -type f ! -path "*/node_modules/*" ! -path "*/.git/*" ! -path "*/vendor/*" ! -path "*/target/*" 2>/dev/null | head -500'
  );

  const files = listResult.stdout
    .split("\n")
    .filter(Boolean)
    .map((f) =>
      f.startsWith("/workspace/") ? f.slice("/workspace/".length) : f
    );

  const contentMap: Record<string, string> = {};
  const configFiles = [
    "package.json",
    "requirements.txt",
    "pyproject.toml",
    "Gemfile",
    "composer.json",
  ];

  for (const cf of configFiles) {
    if (files.includes(cf)) {
      const content = await readSandboxFile(sandboxId, `/workspace/${cf}`);
      if (content) {
        contentMap[cf] = content;
      }
    }
  }

  const { detectTechStack } = (await import(
    "@prometheus/config-stacks"
  )) as typeof import("@prometheus/config-stacks");

  const stack = await detectTechStack(files, contentMap);
  logger.info({ projectId, stack }, "Tech stack detected");
  return stack;
}

async function setupEnvFile(
  sandboxId: string,
  projectId: string
): Promise<boolean> {
  const templateCheck = await execInSandbox(
    sandboxId,
    "ls -1 /workspace/.env.example /workspace/.env.template 2>/dev/null || true",
    10_000
  );

  const templateFile = templateCheck.stdout
    .trim()
    .split("\n")
    .filter(Boolean)[0];

  if (templateFile) {
    const copyResult = await execInSandbox(
      sandboxId,
      `cp "${templateFile}" /workspace/.env`,
      10_000
    );
    return copyResult.exitCode === 0;
  }

  const envContent = [
    "# Auto-generated by Prometheus",
    "NODE_ENV=development",
    "PORT=3000",
    "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/app",
    "REDIS_URL=redis://localhost:6379",
  ].join("\n");

  const writeResult = await execInSandbox(
    sandboxId,
    `cat > /workspace/.env << 'EOF'\n${envContent}\nEOF`,
    10_000
  );

  logger.info(
    { projectId, envFileCreated: writeResult.exitCode === 0 },
    "Environment file setup complete"
  );
  return writeResult.exitCode === 0;
}

function getInstallCommand(packageManager: string): string {
  const commands: Record<string, string> = {
    pnpm: "pnpm install",
    yarn: "yarn install",
    bun: "bun install",
    pip: "pip install -r requirements.txt",
    poetry: "poetry install",
    cargo: "cargo build",
    go: "go mod download",
    bundler: "bundle install",
    composer: "composer install",
  };
  return commands[packageManager] ?? "npm install";
}

// ---------------------------------------------------------------------------
// Main processor
// ---------------------------------------------------------------------------

async function setupGitAuth(
  sandboxId: string,
  projectId: string,
  token: string,
  host?: string
): Promise<boolean> {
  try {
    const response = await fetch(
      `${SANDBOX_MANAGER_URL}/sandbox/${sandboxId}/git`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          operation: "setupAuth",
          token,
          host: host ?? "github.com",
        }),
        signal: AbortSignal.timeout(15_000),
      }
    );

    if (!response.ok) {
      const text = await response.text();
      logger.error(
        { projectId, sandboxId, error: text },
        "Git auth setup failed"
      );
      return false;
    }

    const result = (await response.json()) as { success: boolean };
    return result.success;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error({ projectId, sandboxId, error: msg }, "Git auth setup threw");
    return false;
  }
}

export async function processSetupEnvironment(
  data: SetupProjectEnvironmentData,
  onProgress?: (progress: Record<string, unknown>) => void
): Promise<SetupResult> {
  const { projectId, sandboxId, orgId } = data;

  logger.info({ projectId, sandboxId }, "Starting project environment setup");

  const result: SetupResult = {
    stackDetected: false,
    dependenciesInstalled: false,
    envFileCreated: false,
    buildVerified: false,
    techStack: null,
  };

  // ---- Step 0: Configure git authentication if token provided ----
  if (data.gitToken) {
    onProgress?.({ step: "git_auth", status: "running" });
    const authOk = await setupGitAuth(
      sandboxId,
      projectId,
      data.gitToken,
      data.gitHost
    );
    onProgress?.({
      step: "git_auth",
      status: authOk ? "complete" : "failed",
    });
    if (authOk) {
      logger.info({ projectId, sandboxId }, "Git authentication configured");
    }
  }

  // ---- Step 1: Detect tech stack ----
  onProgress?.({ step: "detect_stack", status: "running" });
  try {
    result.techStack = await detectStack(sandboxId, projectId);
    result.stackDetected = true;
    onProgress?.({
      step: "detect_stack",
      status: "complete",
      stack: result.techStack,
    });
  } catch (err) {
    logger.error({ projectId, err }, "Stack detection failed");
    onProgress?.({ step: "detect_stack", status: "failed" });
  }

  // ---- Step 2: Setup .env from template ----
  onProgress?.({ step: "setup_env", status: "running" });
  try {
    result.envFileCreated = await setupEnvFile(sandboxId, projectId);
    onProgress?.({
      step: "setup_env",
      status: result.envFileCreated ? "complete" : "skipped",
    });
  } catch (err) {
    logger.warn({ projectId, err }, "Env setup failed, continuing");
    onProgress?.({ step: "setup_env", status: "failed" });
  }

  // ---- Step 3: Install dependencies ----
  if (result.techStack) {
    onProgress?.({ step: "install_deps", status: "running" });
    try {
      const pm = result.techStack.packageManager;
      const installCmd = getInstallCommand(pm);
      const installResult = await execInSandbox(
        sandboxId,
        `cd /workspace && ${installCmd}`,
        180_000
      );
      result.dependenciesInstalled = installResult.exitCode === 0;
      logger.info(
        { projectId, pm, success: result.dependenciesInstalled },
        "Dependency installation complete"
      );
      onProgress?.({
        step: "install_deps",
        status: result.dependenciesInstalled ? "complete" : "failed",
        packageManager: pm,
      });
    } catch (err) {
      logger.warn({ projectId, err }, "Dependency install failed, continuing");
      onProgress?.({ step: "install_deps", status: "failed" });
    }
  }

  // ---- Step 4: Verify build ----
  if (result.techStack?.buildCommand && result.dependenciesInstalled) {
    onProgress?.({ step: "verify_build", status: "running" });
    try {
      const buildResult = await execInSandbox(
        sandboxId,
        `cd /workspace && ${result.techStack.buildCommand}`,
        180_000
      );
      result.buildVerified = buildResult.exitCode === 0;
      logger.info(
        {
          projectId,
          buildCommand: result.techStack.buildCommand,
          success: result.buildVerified,
        },
        "Build verification complete"
      );
      onProgress?.({
        step: "verify_build",
        status: result.buildVerified ? "complete" : "failed",
      });
    } catch (err) {
      logger.warn({ projectId, err }, "Build verification failed, continuing");
      onProgress?.({ step: "verify_build", status: "failed" });
    }
  }

  // ---- Publish completion event ----
  try {
    await publisher.publishFleetEvent(orgId, {
      type: "setup_environment_complete",
      data: { projectId, sandboxId, ...result },
      timestamp: new Date().toISOString(),
    });
  } catch {
    // Non-critical
  }

  logger.info({ projectId, ...result }, "Project environment setup complete");
  return result;
}
