/**
 * PR description template generation.
 *
 * Constructs a detailed pull request description from diff context,
 * file change summaries, and agent metadata.
 */

// ── Types ───────────────────────────────────────────────────

export interface FileChangeSummary {
  /** Brief description of what changed in the file */
  description: string;
  /** File path relative to repo root */
  filePath: string;
  /** Number of lines added */
  linesAdded: number;
  /** Number of lines removed */
  linesRemoved: number;
}

export interface PrDescriptionInput {
  /** Files changed with descriptions */
  changedFiles: FileChangeSummary[];
  /** The diff summary (trimmed) */
  diffSummary: string;
  /** Related issue identifiers (e.g. ["#42", "PROJ-123"]) */
  relatedIssues?: string[];
  /** Testing notes or verification steps */
  testingNotes?: string;
  /** High-level summary of the changes */
  title: string;
}

// ── Prompt template ──────────────────────────────────────────

/**
 * Build the system prompt for generating a PR description via an LLM.
 */
export function buildPrDescriptionPrompt(input: PrDescriptionInput): string {
  const filesSection = input.changedFiles
    .map(
      (f) =>
        `- \`${f.filePath}\` (+${f.linesAdded}/-${f.linesRemoved}): ${f.description}`
    )
    .join("\n");

  const issuesSection =
    input.relatedIssues && input.relatedIssues.length > 0
      ? input.relatedIssues.map((i) => `- ${i}`).join("\n")
      : "_None linked_";

  const testingSection = input.testingNotes ?? "_No testing notes provided_";

  return `Given the following changes, generate a clear and detailed pull request description.

Title: ${input.title}

Diff summary:
\`\`\`
${input.diffSummary}
\`\`\`

Generate a PR description following this exact format:

## Summary
Provide a concise 1-3 sentence summary of the overall change and its motivation.

## Changes
${filesSection}

## Testing
${testingSection}

## Related Issues
${issuesSection}
`;
}

// ── Static template builder (no LLM needed) ─────────────────

/**
 * Build a PR description body without an LLM call.
 * Produces well-structured markdown from the structured input.
 */
export function buildPrDescriptionBody(input: PrDescriptionInput): string {
  const lines: string[] = [];

  // Summary section
  lines.push("## Summary");
  lines.push("");
  lines.push(input.title);
  lines.push("");

  // Changes section
  lines.push("## Changes");
  lines.push("");
  if (input.changedFiles.length > 0) {
    const totalAdded = input.changedFiles.reduce(
      (sum, f) => sum + f.linesAdded,
      0
    );
    const totalRemoved = input.changedFiles.reduce(
      (sum, f) => sum + f.linesRemoved,
      0
    );
    lines.push(
      `**${input.changedFiles.length} files changed** (+${totalAdded}/-${totalRemoved})`
    );
    lines.push("");
    lines.push("| File | Changes | Description |");
    lines.push("|------|---------|-------------|");
    for (const f of input.changedFiles) {
      const changes = `+${f.linesAdded}/-${f.linesRemoved}`;
      lines.push(`| \`${f.filePath}\` | ${changes} | ${f.description} |`);
    }
  } else {
    lines.push("_No file change details available._");
  }
  lines.push("");

  // Testing section
  lines.push("## Testing");
  lines.push("");
  if (input.testingNotes) {
    lines.push(input.testingNotes);
  } else {
    lines.push("- [ ] Unit tests pass");
    lines.push("- [ ] Manual verification completed");
    lines.push("- [ ] No regressions observed");
  }
  lines.push("");

  // Related Issues section
  lines.push("## Related Issues");
  lines.push("");
  if (input.relatedIssues && input.relatedIssues.length > 0) {
    for (const issue of input.relatedIssues) {
      lines.push(`- ${issue}`);
    }
  } else {
    lines.push("_None linked_");
  }
  lines.push("");

  // Footer
  lines.push("---");
  lines.push("_Generated by Prometheus AI Agent_");

  return lines.join("\n");
}

// ── Diff parser helper ───────────────────────────────────────

/**
 * Parse a git diff stat output into FileChangeSummary entries.
 *
 * Expects `git diff --stat` output like:
 *   src/foo.ts | 12 +++---
 *   src/bar.ts |  5 +++++
 */
const DIFF_STAT_LINE_RE = /^\s*(.+?)\s*\|\s*(\d+)\s*(\+*)(-*)\s*$/;

export function parseDiffStat(diffStatOutput: string): FileChangeSummary[] {
  const results: FileChangeSummary[] = [];
  const lines = diffStatOutput.split("\n");

  for (const line of lines) {
    // Match: " path/to/file | 12 +++---" or similar
    const match = line.match(DIFF_STAT_LINE_RE);
    if (!match) {
      continue;
    }

    const filePath = (match[1] ?? "").trim();
    const plusCount = (match[3] ?? "").length;
    const minusCount = (match[4] ?? "").length;

    if (!filePath || filePath.includes("changed")) {
      continue;
    }

    results.push({
      filePath,
      linesAdded: plusCount,
      linesRemoved: minusCount,
      description: inferFileChangeDescription(filePath),
    });
  }

  return results;
}

/**
 * Infer a brief description of a file change based on its path.
 */
function inferFileChangeDescription(filePath: string): string {
  const lower = filePath.toLowerCase();

  if (lower.includes("test") || lower.includes("spec")) {
    return "Updated tests";
  }
  if (lower.includes("readme") || lower.includes(".md")) {
    return "Updated documentation";
  }
  if (
    lower.includes("package.json") ||
    lower.includes("lock") ||
    lower.includes("yarn")
  ) {
    return "Updated dependencies";
  }
  if (lower.includes("schema") || lower.includes("migration")) {
    return "Updated database schema";
  }
  if (lower.includes("config") || lower.includes(".env")) {
    return "Updated configuration";
  }
  if (lower.includes("route") || lower.includes("api")) {
    return "Updated API routes";
  }
  if (lower.includes("component") || lower.includes(".tsx")) {
    return "Updated UI component";
  }

  return "Modified";
}
