/**
 * Mock LLM provider for development and testing.
 *
 * When DEV_MOCK_LLM=true, the model-router returns canned responses
 * instead of calling real LLM providers. This enables full pipeline
 * testing without API keys or local Ollama.
 */

import { generateId } from "@prometheus/utils";
import type {
  RouteRequest,
  RouteResponse,
  StreamChunk,
  StreamRouteResult,
} from "./router";

/**
 * Check if mock LLM mode is active.
 */
export function isMockLLMEnabled(): boolean {
  return (
    process.env.DEV_MOCK_LLM === "true" && process.env.NODE_ENV !== "production"
  );
}

/**
 * Generate a mock response based on the request messages.
 * Produces realistic-looking agent responses for common task types.
 */
function generateMockContent(messages: RouteRequest["messages"]): string {
  const lastMessage = messages.at(-1);
  const content = lastMessage?.content?.toLowerCase() ?? "";

  // Detect task type from message content and return appropriate mock response
  if (content.includes("plan") || content.includes("approach")) {
    return `I'll break this task into the following steps:

1. **Analyze requirements** — Understand the scope and constraints
2. **Set up project structure** — Create directories and configuration files
3. **Implement core logic** — Build the main functionality
4. **Add error handling** — Handle edge cases gracefully
5. **Write tests** — Ensure correctness with unit tests
6. **Review and refine** — Polish the implementation

Let me start with step 1.`;
  }

  if (
    content.includes("create") ||
    content.includes("build") ||
    content.includes("implement")
  ) {
    return `I'll implement this now. Here's the code:

\`\`\`typescript
// Generated by Prometheus Agent (mock mode)
import { serve } from "@hono/node-server";
import { Hono } from "hono";

const app = new Hono();

app.get("/", (c) => c.json({ message: "Hello from Prometheus!" }));
app.get("/health", (c) => c.json({ status: "ok", timestamp: new Date().toISOString() }));

serve({ fetch: app.fetch, port: 3000 }, () => {
  console.log("Server running on http://localhost:3000");
});
\`\`\`

I've created a basic Hono server with a health check endpoint. The server is ready to run.`;
  }

  if (
    content.includes("fix") ||
    content.includes("debug") ||
    content.includes("error")
  ) {
    return `I've identified the issue. The problem is a missing null check that causes a runtime error when the input is undefined.

Here's the fix:

\`\`\`diff
- const result = data.value.toString();
+ const result = data?.value?.toString() ?? "";
\`\`\`

This adds optional chaining and a fallback to prevent the TypeError.`;
  }

  if (content.includes("test")) {
    return `Here are the tests:

\`\`\`typescript
import { describe, expect, it } from "vitest";

describe("feature", () => {
  it("should handle valid input", () => {
    const result = processInput("hello");
    expect(result).toBe("HELLO");
  });

  it("should handle empty input", () => {
    const result = processInput("");
    expect(result).toBe("");
  });

  it("should handle null input", () => {
    const result = processInput(null);
    expect(result).toBeNull();
  });
});
\`\`\`

All 3 tests cover the main cases: valid input, empty input, and null input.`;
  }

  // Default response
  return `I've analyzed the request and here's my response:

The task has been completed successfully. I've made the necessary changes following the project conventions and best practices.

Summary of changes:
- Updated the relevant source files
- Added proper error handling
- Ensured type safety throughout
- Followed existing code patterns`;
}

/**
 * Generate mock tool calls if the request includes tools.
 */
function generateMockToolCalls(
  tools: unknown[] | undefined
): unknown[] | undefined {
  if (!tools || tools.length === 0) {
    return undefined;
  }

  // Pick the first tool and generate a mock call
  const firstTool = tools[0] as {
    type?: string;
    function?: { name: string; parameters?: Record<string, unknown> };
  };

  if (firstTool?.function?.name) {
    return [
      {
        id: `call_${generateId().slice(0, 8)}`,
        type: "function",
        function: {
          name: firstTool.function.name,
          arguments: JSON.stringify({ mock: true }),
        },
      },
    ];
  }

  return undefined;
}

/**
 * Handle a route request with mock responses.
 */
export function mockRoute(request: RouteRequest): RouteResponse {
  const content = generateMockContent(request.messages);
  const toolCalls = generateMockToolCalls(
    request.options?.tools as unknown[] | undefined
  );

  return {
    id: `mock_${generateId()}`,
    model: "mock/dev-model",
    provider: "mock",
    slot: request.slot,
    choices: [
      {
        message: {
          role: "assistant",
          content: toolCalls ? "" : content,
          tool_calls: toolCalls,
        },
        finish_reason: toolCalls ? "tool_calls" : "stop",
      },
    ],
    usage: {
      prompt_tokens: 100,
      completion_tokens: 200,
      total_tokens: 300,
      cost_usd: 0,
    },
    routing: {
      primaryModel: "mock/dev-model",
      modelUsed: "mock/dev-model",
      wasFallback: false,
      attemptsCount: 1,
    },
  };
}

/**
 * Handle a streaming route request with mock responses.
 */
export function mockRouteStream(request: RouteRequest): StreamRouteResult {
  const content = generateMockContent(request.messages);
  const words = content.split(" ");

  // Build chunks array and create async iterable
  const chunks: StreamChunk[] = words.map((word, i) => ({
    content: (i === 0 ? "" : " ") + (word ?? ""),
    finishReason: i === words.length - 1 ? "stop" : null,
  }));

  const stream: AsyncIterable<StreamChunk> = {
    [Symbol.asyncIterator]() {
      let index = 0;
      return {
        next() {
          if (index < chunks.length) {
            return Promise.resolve({
              value: chunks[index++] as StreamChunk,
              done: false,
            });
          }
          return Promise.resolve({
            value: undefined as unknown as StreamChunk,
            done: true,
          });
        },
      };
    },
  };

  return {
    id: `mock_${generateId()}`,
    model: "mock/dev-model",
    provider: "mock",
    slot: request.slot,
    stream,
    done: Promise.resolve({
      usage: {
        prompt_tokens: 100,
        completion_tokens: 200,
        total_tokens: 300,
        cost_usd: 0,
      },
      routing: {
        primaryModel: "mock/dev-model",
        modelUsed: "mock/dev-model",
        wasFallback: false,
        attemptsCount: 1,
      },
    }),
  };
}
