export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-20">
      <h1 className="mb-8 font-bold text-4xl text-zinc-100 tracking-tight">
        Terms of Service
      </h1>
      <p className="mb-8 text-sm text-zinc-500">Last updated: March 24, 2026</p>

      <div className="space-y-8 text-zinc-400">
        <section>
          <h2 className="mb-3 font-semibold text-xl text-zinc-200">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using PROMETHEUS (&quot;the Service&quot;), you
            agree to be bound by these Terms of Service. If you are using the
            Service on behalf of an organization, you represent that you have
            the authority to bind that organization to these terms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-semibold text-xl text-zinc-200">
            2. Service Description
          </h2>
          <p>
            PROMETHEUS is an AI-powered engineering platform that uses
            specialist AI agents to assist with software development tasks. The
            Service includes task execution, code generation, project
            management, and related tools accessible through our web application
            and API.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-semibold text-xl text-zinc-200">
            3. Accounts and Credits
          </h2>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              You must provide accurate information when creating an account.
            </li>
            <li>
              You are responsible for maintaining the security of your account
              credentials and API keys.
            </li>
            <li>
              Credits are consumed per task execution. Unused credits on free
              plans expire monthly. Paid plan credits do not roll over unless
              specified.
            </li>
            <li>
              Refunds for purchased credits are available within 14 days of
              purchase if unused.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 font-semibold text-xl text-zinc-200">
            4. Intellectual Property
          </h2>
          <p>
            You retain full ownership of all code, content, and data you provide
            to or generate through the Service. PROMETHEUS does not claim any
            intellectual property rights over your code or project outputs. Code
            generated by AI agents is assigned to you without restriction.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-semibold text-xl text-zinc-200">
            5. Acceptable Use
          </h2>
          <p>You agree not to use the Service to:</p>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>Generate malicious software, malware, or exploit code.</li>
            <li>
              Attempt to circumvent rate limits, credit quotas, or security
              controls.
            </li>
            <li>Violate applicable laws or regulations.</li>
            <li>Infringe on the intellectual property rights of others.</li>
            <li>
              Share account credentials or API keys with unauthorized parties.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 font-semibold text-xl text-zinc-200">
            6. Disclaimers
          </h2>
          <p>
            AI-generated code is provided &quot;as is&quot; without warranty of
            any kind. While PROMETHEUS includes automated testing and security
            audits, you are responsible for reviewing, testing, and validating
            all generated code before deploying to production. PROMETHEUS is not
            liable for issues arising from unreviewed AI-generated code.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-semibold text-xl text-zinc-200">
            7. Service Availability
          </h2>
          <p>
            We strive for 99.9% uptime but do not guarantee uninterrupted
            service. Planned maintenance windows will be communicated in
            advance. Enterprise plans include custom SLA agreements with defined
            uptime guarantees and support response times.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-semibold text-xl text-zinc-200">
            8. Termination
          </h2>
          <p>
            You may cancel your account at any time. We may suspend or terminate
            accounts that violate these terms. Upon termination, your data will
            be retained for 30 days to allow export, then permanently deleted.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-semibold text-xl text-zinc-200">
            9. Contact
          </h2>
          <p>
            For questions about these terms, contact us at{" "}
            <span className="text-violet-400">legal@prometheus.dev</span>.
          </p>
        </section>
      </div>
    </div>
  );
}
